# Generated by Django 4.0.1 on 2022-01-31 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='users_ip',
            field=models.CharField(default='a', max_length=150),
        ),
    ]
