# Generated by Django 4.0.1 on 2022-01-31 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_users_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='users_ip',
        ),
    ]
