# Generated by Django 4.0.1 on 2022-01-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_news_users_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
