# Generated by Django 4.0.1 on 2022-01-31 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='ip_address',
        ),
    ]
